[FEAT] WIP
hannahjavs/react-typescript-project-0 pull request #2
Opened 2018-06-02 11:27 UTC by hannahjavs

2018-06-02 11:27 UTC, hannahjavs commented
hello

2018-06-03 01:42 UTC, bradzacher requested changes
Add the following config to your `tsconfig.json` inside `"compilerOptions"`
```
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "strictNullChecks": true,
```

2018-06-03 01:42 UTC, bradzacher commented on src/app/timetable/TubeService.tsx
> +ListDividers.propTypes = {
You don't need `propTypes` - these are for type checking at runtime in development, which you can get for free at compile time using typescript!

2018-06-03 01:42 UTC, bradzacher commented on src/app/timetable/TubeService.tsx
> +ListDividers.propTypes = {
This will also let you remove the `prop-types` and `@types/prop-types` dependencies.

2018-06-03 01:42 UTC, bradzacher commented on src/app/timetable/TubeService.tsx
> +export function ListDividers(props : ) {
Define your `interface Props` above this then tell typescript the type of `props`

2018-06-03 21:36 UTC, bradzacher commented on src/app/timetable/TubeService.tsx
> +export default Tube withStyles(styles)
`withStyles(styles)(Tube) `

2018-06-03 23:11 UTC, merged